### ISSUE TITLE
Lean more heavily on bullet for conflicts between entities

### ISSUE THREAD

**Issue by chrisforbes** [engineers-nightmare/engineers-nightmare#282]
We should just check for collision rather than trying to reserve space in complex ways

**Comment by Pepe73** [comment]
(10:59:00 PM) pepe731: audio does sound like fun, but back on #282, are you talking about doing away with surf_space?
(10:59:26 PM) chrisf: yeah
(11:00:14 PM) chrisf: more flexible packing of entities on surfaces, and less weird plumbing
(11:00:34 PM) chrisf: surf_space hasnt been delivering much value
(11:03:39 PM) pepe731: the important part that looks like it would be affected is the removal of entities on a surface
(11:05:50 PM) chrisf: the placement validity decision too
(11:06:12 PM) chrisf: but yes, orphaning entities gets harder
(11:06:23 PM) chrisf: we have to solve that anyway for orphaning attaches
(11:06:56 PM) pepe731: is the plan to be able to place entities anywhere relative to surfaces?
(11:07:44 PM) chrisf: yes
(11:07:58 PM) chrisf: or almost anywhere
(11:08:07 PM) chrisf: i think we'll need some snaps
(11:09:33 PM) pepe731: chrisf: so no entities across multiple surfaces?
(11:12:04 PM) chrisf: pepe731, spanning a surface boundary is fine, but no entities sticking into other entities, or through other surfaces
(11:12:37 PM) pepe731: sure, that makes sense
(11:13:19 PM) chrisf: pepe731, any snaps should be subtle what-the-player-wanted-anyway things to help line things up reasonably
(11:21:52 PM) pepe731: That does sound like it could be a bit involved.  Would you see the surface attachement components changing to specify all blocks and faces?
(11:23:54 PM) chrisf: i think maybe they just go away
(11:24:25 PM) chrisf: or are replaced with just the anchor point, or something.
(11:25:00 PM) chrisf: for removal of entities themselves, i think the right thing is to change that tool to raycast against the entities and just remove the hit thing
(11:25:11 PM) chrisf: rather than trying to go via the block grid at all
(11:25:31 PM) pepe731: right, I was more concerned about removing surfaces under entities
(11:27:53 PM) chrisf: right, we need to define how the test for being orphaned actually works
(11:28:49 PM) chrisf: do we sample rays out the back of the entity and insist on a hit near the expected distance?
(11:29:31 PM) chrisf: if that's the approach, where should they be placed? how many must succeed to consider the thing still attached?
(11:31:14 PM) pepe731: it seems you would have to define the sample pattern per mesh
(11:31:31 PM) chrisf: unless it's something simple like one, through the origin
(11:32:04 PM) chrisf: we do have support for marking things in the mesh in the art tool
(11:32:09 PM) RobotCaleb: chrisf: can we get percent overlap from bullet?
(11:32:13 PM) chrisf: (used for baked in attachment points)
(11:32:44 PM) chrisf: RobotCaleb, you may have to define that a bit more precisely
(11:33:17 PM) RobotCaleb: https://awwapp.com/b/uhppava5m/
(11:33:42 PM) RobotCaleb: ugh
(11:33:44 PM) RobotCaleb: I can't draw!
(11:34:05 PM) pepe731: you are talking overlap of back of entity mesh with surface?
(11:34:58 PM) chrisf: RobotCaleb, body-body collision tests in bullet are just (tweaked) GJK.
(11:35:18 PM) RobotCaleb: There
(11:35:21 PM) RobotCaleb: Can you see that?
(11:35:24 PM) chrisf: yes
(11:35:50 PM) RobotCaleb: if x% of placement collider is overlapped, allow
(11:36:50 PM) chrisf: so no, there are no volume or area checks.
(11:37:00 PM) RobotCaleb: alright
(11:37:14 PM) chrisf: that requires a lot more structure than it has
(11:37:24 PM) RobotCaleb: we could take the bottom of our mesh and the surface it's colliding with and do something similar to http://www.angusj.com/delphi/clipper.php
(11:37:54 PM) RobotCaleb: unless we think raytraces from some rule of locations is good enough
(11:38:16 PM) chrisf: i think raycasts are /plenty/
(11:38:26 PM) pepe731: you could make a "mounting bracket" mesh and raycast from that
(11:39:05 PM) chrisf: are the rules for placement the same as the rules that would cause the entity to be orphaned?
(11:39:25 PM) RobotCaleb: a superset
(11:40:27 PM) pepe731: I would add to placement ensuring no entity collisions, but otherwise yes
(11:40:43 PM) RobotCaleb: placement will care about penetrating in walls and other entities. orphaning won't occur in the latter, but maybe the former?
(11:40:50 PM) chrisf: for sampling points, assuming rectangular entities, a first rough cut might be for small entities, one sample through the origin; for large entities, 4: at .25/.75 of the size on the other two axes
(11:41:54 PM) chrisf: this affects block placement too
(11:42:11 PM) chrisf: and surface placement, i suppose.
(11:43:21 PM) chrisf: (both can be blocked by existing surface entities that would intersect with the newly placed surface/block?)
